baseURL = 'https://unitigris.github.io/HETIC-gitpages/'
languageCode = 'fr-fr'
title = "SKELETON'S BLOG"
theme = 'ananke'

[params]
favicon = "/HETIC-gitpages/img/favicon.png"
site_logo = "/HETIC-gitpages/img/favicon-head.png"
bg_image = "/HETIC-gitpages/img/bgskeleton.jpg"
sub = 'Etudiant en MT4 à HETIC'


[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    url = "/posts"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2


# Paramètres spécifiques au thème Ananke
showReadingTime = true
